apiVersion: apps/v1
kind: Deployment

metadata:
  name: firstdeployment
  namespace: gsbmweb
  labels:
    appname: votingapp
  annotations:
    kubernetes.io/change-cause: "we are migrating from cusotm image to Nginx."

spec:
  replicas: 5
  minReadySeconds: 30
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchExpressions:
      - key: type
        operator: In
        values:
          - app
          - backend
  template:
    metadata:
      name: firstPod1
      labels:
        type: app
    spec:
      containers:
        - image: nginx
          name: firstcontainer

