apiVersion: v1
kind: Pod
metadata:
  name: myfirstpod
  labels:
    env: Test
    test: DEV
    test1: PROD

spec:
  containers:
    - name: firstconntainer
      image: coolgourav147/nginx-custom
      envFrom:
        - configMapRef:
            name: mycm

  