apiVersion: v1
kind: ReplicationController

metadata:
  name: firstrc
  labels:
    appname: votingapp

spec:
  replicas: 5
  template:
    metadata:
      name: firstPod1
      labels:
        type: app
    spec:
      containers:
        - image: coolgourav147/nginx-custom
          name: firstcontainer

