apiVersion: v1
kind: Pod
metadata:
  name: myfirstpod
  labels:
    env: Test
    test: DEV
    test1: PROD

spec:
  containers:
    - name: firstconntainer
      image: coolgourav147/nginx-custom
      env:
        - name: JAVA_HOME
          value: /usr/bin/jdk
      args: [ "sleep" , "3600"]
    - name: secondcontainer
      image: coolgourav147/nginx-custom
      env:
        - name: PYTHON_HONME
          value: /usr/bin/python
  initContainers:
    - name: firstconntainerinit
      image: coolgourav147/nginx-custom
      env:
        - name: JAVA_HOME
          value: /usr/bin/jdk
      args: [ "sleep" , "30"]
    - name: secondcontainerinit
      image: ubuntu
      env:
        - name: PYTHON_HONME
          value: /usr/bin/python                  
      args: [ "sleep" , "30"]
      