apiVersion: v1
kind: Pod
metadata:
  name: mysecondpodreplica
  labels:
    env: Test
    test: DEV
    test1: PROD
    type: webserver

spec:
  containers:
    - name: firstconntainer
      image: nginx
      env:
        - name: JAVA_HOME
          value: /usr/bin/jdk
    
      